server:
  port: 8080

spring:
  application:
    name: ead-gateway-api
  cloud:
    gateway:
      # Rotas do gateway
      # lb: Load Balancer
      routes:
       - id: auth-user-api
         uri: lb://ead-auth-user-api
         predicates:
          - Path=/ead-auth-user/**
       - id: course-api
         uri: lb://ead-course-api
         predicates:
          - Path=/ead-course/**
       - id: notification-api
         uri: lb://ead-notification-api
         predicates:
          - Path=/ead-notification/**

ead:
  serviceRegistry:
    username: serviceRegistry
    password: ${SERVICE_REGISTRY_PASSWORD}

# Eureka server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'